# Generated by Django 4.1.13 on 2026-01-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_alter_student_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classe',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
